CREATE TABLE [dbo].[Employees] (
[Id] [int] IDENTITY(1,1) NOT NULL,
[FirstName] [varchar] (50) NOT NULL,
[LastName] [varchar](50) NOT NULL,
[DateOfBirth] [date] NOT NULL,
[Email] [nvarchar] (50) NOT NULL,
[Salary] [float] NOT NULL,
)
--CONSTRAINT [PK_Employees] PRIMARY KEY CLUSTERED
--([Id] ASC
-- )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON
--) ON [PRIMARY]
--GO